import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, Menu, X, ChevronRight, Send, ShieldCheck, Scale, Users, Brain, BriefcaseBusiness, MapPin, Mail} from 'lucide-react';
import './styles.css';

const asset=(name:string)=>`${import.meta.env.BASE_URL}assets/${name}`;

const businessServiceGroups=[
 {title:'Собственнику и руководителю',services:[
  {price:'6 000 ₽ / 60 минут',title:'Индивидуальная консультация бизнес-психолога',text:'Разбираем рабочую ситуацию, ваши переживания и возможные действия, чтобы определить следующий шаг.'},
  {price:'22 000 ₽ / 4 встречи по 60 минут',title:'Регулярное психологическое сопровождение руководителя',text:'Встречи для работы с повторяющимися трудностями, нагрузкой и отношениями в бизнесе.'},
  {price:'6 000 ₽ / 60 минут',title:'Работа с выгоранием, перегрузкой и потерей интереса к бизнесу',text:'Исследуем источники истощения, пересматриваем нагрузку и ищем способы восстановить силы и интерес к работе.'},
  {price:'8 000 ₽ / 90 минут',title:'Помощь в принятии сложных решений',text:'Проясняем варианты, внутренние противоречия и последствия. Решение остаётся за вами.'},
  {price:'6 000 ₽ / 60 минут',title:'Работа с гиперконтролем и трудностями делегирования',text:'Разбираем, что мешает доверять команде, и определяем границы контроля и передачи задач.'},
  {price:'22 000 ₽ / 4 встречи',title:'Сопровождение перехода в новую управленческую роль',text:'Помогаю освоиться после повышения, смены компании или выхода из операционного управления.'},
  {price:'8 000 ₽ / 90 минут',title:'Развитие управленческих навыков и лидерства',text:'На ваших рабочих ситуациях разбираем постановку задач, обратную связь, границы и ответственность руководителя.'}
 ]},
 {title:'Оценка кандидатов и сотрудников',services:[
  {price:'10 000 ₽ / человек',title:'Психологическая диагностика кандидата при приёме на работу',text:'Оцениваем мотивацию, стиль взаимодействия и поведение в рабочих ситуациях с учётом требований должности.'},
  {price:'от 20 000 ₽ / человек',title:'Углублённая оценка кандидата на руководящую должность',text:'Изучаем управленческий опыт, способы принятия решений и взаимодействия с командой. Обсуждаем сильные стороны и возможные риски.'},
  {price:'25 000 ₽ / пара',title:'Оценка особенностей взаимодействия кандидата с будущим руководителем',text:'Сопоставляем рабочие ожидания и стили общения, определяем возможные точки напряжения и условия сотрудничества.'},
  {price:'от 20 000 ₽ / человек',title:'Оценка действующего руководителя',text:'Исследуем компетенции, стиль управления и потенциал развития, формулируем рекомендации для дальнейшей работы.'},
  {price:'12 000 ₽ / человек',title:'Оценка сотрудников перед повышением или переводом',text:'Сопоставляем опыт и особенности сотрудника с новой ролью, определяем необходимую поддержку при переходе.'},
  {price:'от 60 000 ₽ / проект',title:'Оценка управленческой команды',text:'Рассматриваем сильные стороны участников, распределение ролей и то, как команда принимает совместные решения.'},
  {price:'от 15 000 ₽ / оцениваемый сотрудник',title:'Оценка «360 градусов»',text:'Собираем и разбираем обратную связь от руководителя, коллег и подчинённых, выделяем направления развития.'},
  {price:'от 80 000 ₽ / проект',title:'Ассессмент-центр',text:'Оценка рабочих компетенций через деловые задания и наблюдение по заранее согласованным критериям.'},
  {price:'от 60 000 ₽ / проект',title:'Формирование кадрового резерва и индивидуальных планов развития',text:'Определяем перспективные роли для сотрудников и составляем план развития под задачи компании.'}
 ]},
 {title:'Бизнес-партнёрам и предпринимательской семье',services:[
  {price:'от 40 000 ₽ / проект',title:'Подготовка договорённостей перед началом совместного бизнеса',text:'Обсуждаем цели, вклад, роли, деньги и порядок принятия решений до запуска партнёрства.'},
  {price:'30 000 ₽ / подготовка и встреча до 3 часов',title:'Рабочая встреча бизнес-партнёров',text:'Проясняем ожидания, роли и ответственность, фиксируем договорённости по вопросам, которые откладывались.'},
  {price:'от 60 000 ₽ / проект',title:'Сопровождение конфликта между совладельцами',text:'Помогаю организовать разговор об интересах сторон, причинах разногласий и возможных вариантах выхода из конфликта.'},
  {price:'от 40 000 ₽ / проект',title:'Пересмотр условий партнёрства',text:'Разбираем, какие договорённости перестали работать и что нужно изменить в распределении ролей и ответственности.'},
  {price:'от 80 000 ₽ / проект',title:'Сопровождение выхода одного из партнёров из бизнеса',text:'Помогаю подготовить сложные переговоры, обсудить ожидания сторон и последовательность перехода.'},
  {price:'от 100 000 ₽ / проект',title:'Психологическое сопровождение передачи семейного бизнеса и управления',text:'Работаем с ожиданиями поколений, доверием и изменением ролей в семье и компании.'},
  {price:'12 000 ₽ / совместная встреча до 90 минут',title:'Консультирование по вопросам семейных и деловых отношений',text:'Разбираем ситуации, в которых семейные переживания и решения в бизнесе влияют друг на друга.'}
 ]},
 {title:'Команда и система управления',services:[
  {price:'от 40 000 ₽ / проект',title:'Диагностика взаимодействия и распределения ролей в команде',text:'Выясняем, где возникают сбои в коммуникации, дублирование задач и размытая ответственность.'},
  {price:'от 30 000 ₽ / проект',title:'Разбор конфликтов между сотрудниками, руководителями или подразделениями',text:'Исследуем причины напряжения и помогаем участникам выработать рабочие договорённости.'},
  {price:'от 40 000 ₽ / сессия до 4 часов с подготовкой',title:'Командная сессия для выработки рабочих договорённостей',text:'Проводим общую встречу, чтобы согласовать правила взаимодействия, порядок решений и ответственность за задачи.'},
  {price:'от 70 000 ₽ / рабочий день с подготовкой',title:'Стратегическая сессия для руководителей',text:'Организуем обсуждение целей и приоритетов компании, фиксируем решения, ответственных и следующие шаги.'},
  {price:'от 60 000 ₽ / месяц',title:'Сопровождение организационных изменений',text:'Разбираем реакцию команды на перемены, готовим коммуникацию и поддержку руководителей в переходный период.'},
  {price:'от 60 000 ₽ / проект',title:'Разработка организационной структуры, распределение полномочий и ответственности',text:'Соотносим структуру с задачами бизнеса, проясняем роли, зоны ответственности и порядок взаимодействия.'},
  {price:'от 60 000 ₽ / проект',title:'Диагностика и развитие корпоративной культуры',text:'Исследуем действующие нормы и привычки команды, определяем, какие из них поддерживают цели компании, а какие мешают.'},
  {price:'15 000 ₽ / разбор до 2 часов с подготовкой',title:'Консультирование по мотивации персонала',text:'Разбираем, что влияет на вовлечённость сотрудников, и подбираем подходы к мотивации с учётом задач бизнеса.'}
 ]},
 {title:'Психологическая поддержка и обучение сотрудников',services:[
  {price:'4 000 ₽ / 60 минут',title:'Индивидуальные консультации сотрудников за счёт работодателя',text:'Личные встречи для работы с напряжением и трудными ситуациями. Границы конфиденциальности согласуются до начала работы.'},
  {price:'от 40 000 ₽ / месяц',title:'Регулярная программа психологической поддержки компании',text:'Составляем программу консультаций и групповых мероприятий с понятным порядком обращения и согласованным графиком.'},
  {price:'от 25 000 ₽ / групповой практикум до 3 часов',title:'Профилактика профессионального выгорания',text:'Помогаем замечать признаки перегрузки, обсуждаем рабочие условия и способы восстановления.'},
  {price:'от 20 000 ₽ / мероприятие до 2 часов',title:'Лекции и практикумы по управлению стрессом',text:'Разбираем реакции на стресс и осваиваем практические способы справляться с напряжением в рабочем дне.'},
  {price:'от 35 000 ₽ / тренинг до 4 часов',title:'Тренинги по коммуникации и работе с конфликтами',text:'На рабочих примерах тренируем обратную связь, сложные разговоры и поиск договорённостей.'},
  {price:'от 40 000 ₽ / тренинг до 4 часов',title:'Обучение руководителей взаимодействию с командой',text:'Практикуем постановку задач, обсуждение ошибок, поддержку сотрудников и разговоры о результатах.'}
 ]}
];

const businessPricingNotes=[
 'Пакет из четырёх встреч — согласованный объём работы. Продолжительность сопровождения зависит от задачи и обсуждается индивидуально.',
 'Индивидуальная диагностика включает интервью, согласованные методики, письменное заключение и обсуждение результатов. Для командных проектов заранее определяем число участников и объём оценки.',
 'Состав юридической работы согласуется заранее: изучение документов, подготовка соглашений и участие в переговорах включаются в стоимость в пределах оговорённого объёма.',
 'Для месячного сопровождения заранее устанавливаем количество встреч и перечень работ. Разработка системы мотивации целиком рассчитывается отдельно от консультации.',
 'Базовая программа за 40 000 ₽ в месяц включает восемь индивидуальных консультаций и одну групповую встречу до часа. Число участников групповых мероприятий согласуется заранее.'
];

const personalSituations=[
 {title:'Не понимаю, куда двигаться дальше',text:'Когда прежние ориентиры больше не помогают, а новое решение ещё не появилось.'},
 {title:'Тревога не отпускает',text:'Когда мысли постоянно возвращаются к плохому сценарию и трудно почувствовать опору.'},
 {title:'Отношения стали источником боли',text:'Когда разговоры не помогают, близость исчезает или один и тот же конфликт повторяется.'},
 {title:'Переживаю расставание или развод',text:'Когда нужно выдержать перемены, сохранить себя и принимать непростые решения.'},
 {title:'Трудно защищать свои границы',text:'Когда сложно отказать, попросить о важном или перестать жить по чужим ожиданиям.'},
 {title:'Внешне всё хорошо, а внутри пусто',text:'Когда привычная жизнь продолжается, но в ней больше нет радости, смысла или живого интереса.'}
];

const psychologistLegalSituations=[
 {title:'Договор с клиентом',text:'Подготовка понятных условий работы: формат встреч, оплата, отмена, перенос и границы ответственности.'},
 {title:'Персональные данные',text:'Согласия, анкеты и правила хранения информации, которую психолог получает от клиента.'},
 {title:'Сайт и запись на консультацию',text:'Проверка формы записи, обязательных документов, описания услуг и публичных текстов.'},
 {title:'Конфликт или претензия клиента',text:'Разбор ситуации, переписки и возможных действий без лишней эскалации.'},
 {title:'Начало частной практики',text:'Юридическая основа работы, порядок оплаты и документы, необходимые на старте.'},
 {title:'Реклама и экспертный контент',text:'Проверка формулировок, обещаний результата и границ между психологической и медицинской помощью.'}
];

const posts=[
 {slug:'ne-speshit',tag:'РЕШЕНИЯ',title:'Не спешить — не значит ничего не делать',lead:'Как отделить срочность эмоции от срочности решения и вернуть себе управляемость.',read:'6 минут',body:['В кризисе скорость легко спутать с эффективностью. Чем выше тревога, тем сильнее хочется немедленно закрыть вопрос — подписать, уволить, разорвать партнёрство или согласиться на первый предложенный сценарий.','Пауза нужна не для ухода от решения. Она нужна, чтобы разделить факты, интерпретации, риски и последствия. После этого действие становится не медленнее, а точнее.','Первый шаг — назвать, что именно требует решения сегодня, а что может подождать до появления полной картины.']},
 {slug:'konflikt-partnerov',tag:'ПАРТНЁРСТВО',title:'Когда конфликт партнёров становится проблемой бизнеса',lead:'Пять признаков, что личный спор уже меняет экономику и управление компанией.',read:'8 минут',body:['Конфликт становится бизнес-проблемой не в момент громкого разговора, а когда решения начинают приниматься в обход общей логики.','Сигналы: параллельные договорённости, задержка ключевых решений, борьба за лояльность команды, информационные закрытые зоны и перенос личных претензий в управленческие процедуры.','Работа начинается не с поиска виноватого, а с карты интересов, полномочий, рисков и минимально возможного соглашения.']},
 {slug:'tri-izmereniya',tag:'МЕТОД',title:'Почему одного специалиста иногда недостаточно',lead:'Что теряется, если смотреть на дорогой кризис только глазами права или только глазами психологии.',read:'7 минут',body:['Юридически безупречное решение может оказаться психологически неисполнимым. Психологически комфортное — создать правовые и управленческие риски.','Поэтому сложная ситуация рассматривается одновременно в трёх измерениях: человек, право и система. Это не замена профильных специалистов, а единая карта, которая помогает увидеть связи между их рекомендациями.','Цель — решение, которое клиент понимает, принимает и способен выполнить.']}
];

const products=[
 {kicker:'ЛЁГКИЙ ПЛАТНЫЙ ВХОД',title:'Карта решения',price:'Пилот · 4 900 ₽',text:'35–45 минут и письменная карта: факты, главный узел, цена паузы, зона контроля и ближайший исполнимый шаг.'},
 {kicker:'ОСНОВНОЙ B2C-ПРОДУКТ',title:'Точка ясности',price:'4 недели · пилот 39 000 ₽',text:'Четыре встречи, критерии решения, подготовка сложного разговора и план действий на ближайшие 30 дней.'},
 {kicker:'ОСНОВНОЙ B2B-ПРОДУКТ',title:'Передача без потери',price:'Диагностика · пилот 120 000 ₽',text:'Карта полномочий, риски перехода, правила эскалации и дорожная карта передачи управления на 30/60/90 дней.'}
];

function Logo(){return <a className="logo" href="#top"><span>ОЛЬГА</span><small>БОРЗЕНКОВА</small></a>}
function Header(){const [open,setOpen]=useState(false);return <header><div className="headerBrand"><Logo/><span className="headerRole">Кризисный консультант с высшим юридическим и психологическим образованием</span></div><button className="menuButton" aria-label="Меню" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''} onClick={()=>setOpen(false)}><a href="#socials">Социальные сети</a><a className="navCta" href="#contact">Записаться на встречу</a><a className="navPrice" href="#pricing">Стоимость</a><a href="#documents">Документы</a><a href="#office">Адрес</a></nav></header>}

function Home(){return <><div id="top"/><section className="hero"><Header/><div className="heroShade"/><div className="heroCopy"><p className="eyebrow light">ЧЕЛОВЕК · СИСТЕМА · ПРАВО</p><h1 className="heroPromise">Я буду держать тебя за руку,<br/><span>пока твой привычный мир разваливается на части,</span></h1><p className="heroPromiseContinuation">помогая вернуть ясность, найти опору, принять решение и сделать следующий шаг.</p><div className="heroActions"><a className="button copper" href="#personal">Личные вопросы <ArrowRight size={18}/></a><a className="button outline" href="#business">Бизнес <ArrowRight size={18}/></a><a className="button outline" href="#psychologist-law">Юрист для психологов <ArrowRight size={18}/></a></div></div></section>
<main>
<section className="about aboutFacts" id="about">
<div className="sectionHead"><h2>Обо мне в фактах</h2></div>

<div className="factsGrid">
<div className="aboutFact"><h3>Высшее образование</h3><p>Иркутский государственный университет, юридический институт.</p><p>Иркутский государственный университет, факультет психологии.</p></div>
<div className="aboutFact"><h3>Магистратура</h3><p>Иркутский государственный медицинский университет<br/>Консультативная психология и психотерапия</p></div>
<div className="aboutFact"><h3>Аспирантура</h3><p>Байкальский государственный университет<br/>Кафедра уголовного права и криминологии</p></div>
<div className="aboutFact"><h3>22 года — в корпоративном праве и адвокатуре.</h3></div>
<div className="aboutFact"><h3>Аттестованный специалист по управлению персоналом и кадровой работе.</h3></div>
<div className="aboutFact"><p><strong>Консалтинг и инхаус крупного бизнеса</strong> — нефтяные компании, строительные холдинги, университеты, собственники и руководители.</p></div>
<div className="aboutFact"><p><strong>Преподаватель</strong> — криминология, уголовное право, уголовно-исполнительное право, трудовое право, гражданский и арбитражный процесс.</p></div>
<div className="aboutFact"><p><strong>3 языка</strong> — русский, английский, французский.</p></div>
<div className="aboutFact"><p><strong>4 детей</strong> — мой личный курс по управлению хаосом, переговорам и многозадачности и о том, как восстать из декрета.</p></div>
<div className="aboutFact"><p><strong>КМС по плаванию</strong> — умею держать темп и не тонуть, даже когда дистанция длинная.</p></div>
<div className="aboutFact"><p><strong>Победитель городских соревнований по смешанным единоборствам</strong> — знаю, что иногда для движения вперёд нужна не только голова, но и характер.</p></div>
<div className="aboutFact"><p><strong>Лучший молодой писатель года России</strong> — умею придавать форму тому, что трудно выразить словами.</p></div>
</div>
<div className="aboutClosing"><p><strong>И ещё один факт: я не боюсь сложных поворотов — ни в жизни, ни в бизнесе.</strong></p><p>Когда привычный мир разваливается, я не обещаю собрать его за тебя.</p><p><strong>Я помогу тебе собрать себя — и уже из этого места решить, что делать дальше.</strong></p></div>
</section>
<section className="statement" id="approach"><p className="eyebrow">ГЛАВНЫЙ ПРИНЦИП</p><h2>У каждой сложной ситуации<br/><em>три измерения.</em></h2><p>Каждый личный выбор всегда затрагивает жизнь самого человека, систему, в которой он существует, и имеет правовые последствия. Я помогаю увидеть все три измерения проблемы и собрать решение, которое можно реализовать.</p><div className="triad"><div><span>01</span><h3>Человек</h3><p>Его чувства, мотивы, потребности и способность выполнить решение.</p></div><div><span>02</span><h3>Система</h3><p>Семья, бизнес, общество и государство: связи, роли и последствия для других людей.</p></div><div><span>03</span><h3>Право</h3><p>Юридические риски, обязанности, границы и действия, необходимые для реализации решения.</p></div></div></section>
<section className="directions"><div className="sectionHead"><p className="eyebrow">ТРИ НАПРАВЛЕНИЯ РАБОТЫ</p><h2>С чем вы хотите<br/><em>разобраться?</em></h2><p>Какой бы путь вы ни выбрали, мы будем смотреть на ситуацию целиком: что происходит с человеком, как устроена окружающая его система и какие правовые последствия может иметь решение.</p></div><div className="directionGrid"><a href="#personal" className="directionCard personalDirection"><span>01</span><h3>Личные вопросы</h3><p>Человек, его отношения и жизненные решения — с учётом интересов семьи, работы и возможных последствий.</p><b>Посмотреть ситуации <ArrowRight size={17}/></b></a><a href="#business" className="directionCard businessDirection"><span>02</span><h3>Бизнес</h3><p>Собственник, команда и компания — с учётом человеческих мотивов, бизнес-процессов и требований законодательства.</p><b>Посмотреть ситуации <ArrowRight size={17}/></b></a><a href="#psychologist-law" className="directionCard legalDirection"><span>03</span><h3>Юрист для психологов</h3><p>Создание юридически защищённой системы частной практики с учётом прав и законных интересов психолога и клиента.</p><b>Посмотреть ситуации <ArrowRight size={17}/></b></a></div></section>
<section className="personalServices" id="personal"><div className="sectionIntroWithPhoto servicePhotoBackground"><div className="sectionHead"><p className="eyebrow">ЛИЧНЫЕ ВОПРОСЫ</p><h2>Когда важно разобраться<br/><em>в себе и своей жизни</em></h2></div><img className="sectionInsetPhoto wideCrop" src={asset('olga-personal-photo-3.jpg')} alt="Ольга Борзенкова"/></div><div className="personalGrid">{personalSituations.map((s,i)=><article className="personalCard" key={s.title}><span>0{i+1}</span><h3>{s.title}</h3><p>{s.text}</p><a href="#contact">Обсудить на встрече <ArrowRight size={17}/></a></article>)}</div></section>
<section className="situations" id="business"><div className="sectionIntroWithPhoto servicePhotoBackground"><div className="sectionHead"><p className="eyebrow">БИЗНЕС</p><h2>Когда решение влияет<br/>не только на вас</h2><p>В бизнесе личное решение собственника меняет всю систему: команду, деньги, отношения и ответственность. Поэтому мы одновременно учитываем человека, устройство бизнеса и право.</p></div><img className="sectionInsetPhoto" src={asset('olga-principle.webp')} alt="Ольга Борзенкова за шахматной доской"/></div><div className="businessServices"><p className="businessServicesHint">Выберите направление — раскройте список услуг</p>{businessServiceGroups.map((group,i)=><details className="businessServiceGroup" key={group.title}><summary><span className="businessGroupNumber">0{i+1}</span><span className="businessGroupTitle">{group.title}</span><span className="businessGroupCount">{group.services.length} услуг</span><ChevronRight className="businessGroupChevron" size={24}/></summary><div className="businessGroupContent"><ul className="businessServiceList">{group.services.map(service=><li key={service.title}><h3>{service.title}</h3><p>{service.text}</p></li>)}</ul><a className="businessGroupCta" href="#contact">Обсудить задачу<ArrowRight size={18}/></a></div></details>)}</div></section>
<section className="lawForPsychologists" id="psychologist-law"><div className="sectionIntroWithPhoto servicePhotoBackground"><div className="sectionHead"><p className="eyebrow">ЮРИСТ ДЛЯ ПСИХОЛОГОВ</p><h2>Чтобы практика была<br/><em>понятной и защищённой</em></h2><p>Документы должны защищать право, поддерживать рабочую систему и оставаться понятными живым людям — психологу и его клиенту.</p></div><img className="sectionInsetPhoto" src={asset('olga-hero-natural-face-v5.webp')} alt="Ольга Борзенкова в рабочем кабинете"/></div><div className="legalGrid">{psychologistLegalSituations.map((s,i)=><article className="legalCard" key={s.title}><span>0{i+1}</span><h3>{s.title}</h3><p>{s.text}</p><a href="#contact">Обсудить задачу <ArrowRight size={17}/></a></article>)}</div></section>

<section className="pricing" id="pricing">
<div className="sectionHead"><p className="eyebrow">СТОИМОСТЬ УСЛУГ</p><h2>Форматы и стоимость</h2></div>
<div className="pricingGrid">
<article className="pricingCard pricingPersonal"><h3>Личные вопросы</h3><dl className="pricingOptions"><div><dt>Одна сессия</dt><dd>4 000 ₽</dd></div><div><dt>При бронировании 10 сессий</dt><dd>3 500 ₽ <span>за сессию</span></dd><dd className="pricingNote">35 000 ₽ за 10 сессий</dd></div></dl><a className="pricingCta" href="#contact">Записаться на встречу <ArrowRight size={17}/></a></article>
<article className="pricingCard pricingLegal"><h3>Юрист для психологов</h3><dl className="pricingOptions"><div><dt>Консультация</dt><dd>5 000 ₽</dd></div><div><dt>Пакет документов</dt><dd>4 000 ₽</dd></div></dl><a className="pricingCta" href="#contact">Обсудить задачу <ArrowRight size={17}/></a></article>
<article className="pricingCard pricingBusiness"><h3>Бизнес</h3><p className="pricingDetails">Пять направлений работы — выберите блок, чтобы посмотреть стоимость услуг. Окончательная стоимость проектов определяется после обсуждения задачи, числа участников и объёма работы.</p><div className="businessServices">{businessServiceGroups.map((group,i)=><details className="businessServiceGroup" key={group.title}><summary><span className="businessGroupNumber">0{i+1}</span><span className="businessGroupTitle">{group.title}</span><span className="businessGroupCount">{group.services.length} услуг</span><ChevronRight className="businessGroupChevron" size={24}/></summary><div className="businessGroupContent"><dl className="businessPriceList">{group.services.map(service=><div key={service.title}><dt>{service.title}{service.title==='Ассессмент-центр'&&' (оценка рабочих и управленческих компетенций с помощью деловых заданий, моделирования рабочих ситуаций и наблюдения экспертов)'}</dt><dd>{service.price}</dd></div>)}</dl><p className="businessPriceNote">{businessPricingNotes[i]}</p><a className="businessGroupCta" href="#contact">Обсудить задачу<ArrowRight size={18}/></a></div></details>)}</div></article>
</div></section>
<section className="documents" id="documents"><div className="sectionHead"><p className="eyebrow light">ДОКУМЕНТЫ</p><h2>Всё важное —<br/><em>до первой встречи</em></h2></div><div className="documentGrid"><article><Scale size={28}/><h3>Договор об оказании услуг</h3><p>Предмет работы, формат встреч, стоимость, порядок оплаты, отмены и прекращения работы.</p><span>Направляется после записи на встречу</span></article><article><ShieldCheck size={28}/><h3>Согласие на обработку данных</h3><p>Какие сведения нужны для записи, для чего они используются и как защищаются.</p><span>Направляется после записи на встречу</span></article><article><Brain size={28}/><h3>Информированное согласие</h3><p>Возможности и границы психологического консультирования, права клиента и порядок взаимодействия.</p><span>Направляется после записи на встречу</span></article></div></section>
<section className="blog" id="blog"><div className="sectionHead"><p className="eyebrow">ЛИЧНЫЙ БЛОГ ПСИХОЛОГА</p><h2>Психология:<br/><em>великая и ужасная</em></h2><p>О том, как внутренние переживания человека становятся решениями, меняют систему отношений и иногда приводят к правовым последствиям.</p></div><div className="postGrid">{posts.map(p=><a className="post" href={`#/blog/${p.slug}`} key={p.slug}><span>{p.tag}</span><h3>{p.title}</h3><p>{p.lead}</p><small>{p.read} <ArrowRight size={15}/></small></a>)}</div></section>
<section className="socials" id="socials"><div className="sectionHead"><p className="eyebrow">ОСТАВАЙТЕСЬ НА СВЯЗИ</p><h2>Больше мыслей и разговоров<br/><em>в моих каналах.</em></h2><p>Выберите удобную площадку — короткие видео, заметки и материалы о сложных решениях.</p></div><div className="socialGrid"><a href="https://youtube.com/channel/UC2ZPOXNBx7PzwgtqHkazaRg?si=ESOn5pOVVXnTy_wx" target="_blank" rel="noreferrer"><span className="socialMark">YT</span><span>YouTube</span><ArrowRight size={17}/></a><a href="https://www.instagram.com/olgaborzenkovapsy/" target="_blank" rel="noreferrer"><span className="socialMark">IG</span><span>Instagram</span><ArrowRight size={17}/></a><a href="https://m.tenchat.ru/u/lo5xce9o" target="_blank" rel="noreferrer"><span className="socialMark">T</span><span>TenChat</span><ArrowRight size={17}/></a><a href="https://max.ru/join/nt1En70ad4uq4RO3Rh2e1HK0SFfUoISLDRxKTrJoL-A" target="_blank" rel="noreferrer"><span className="socialMark">M</span><span>MAX канал</span><ArrowRight size={17}/></a><a href="https://t.me/tochkayasno" target="_blank" rel="noreferrer"><span className="socialMark">TG</span><span>Telegram канал</span><ArrowRight size={17}/></a></div></section>
<section className="contact" id="contact"><div className="contactIntro"><p className="eyebrow light">ПЕРВЫЙ ШАГ</p><h2>Записаться<br/>на встречу.</h2><p>Коротко опишите ситуацию. На встрече мы рассмотрим её в трёх измерениях: человек, система и право — и определим понятный следующий шаг.</p></div><a className="button ivory" href="https://t.me/Olga_Sergeevna_Borzenkova" target="_blank" rel="noreferrer"><Send size={18}/>Записаться на встречу</a></section>
<section className="office" id="office"><div className="officeTitle"><p className="eyebrow">ЛИЧНАЯ ВСТРЕЧА</p><h2>Пространство для<br/><em>важного разговора.</em></h2><p>г. Иркутск, ул. Горная, 24<br/>бизнес-центр «Зеркальный», 8 этаж, офис 804</p><img className="officePhoto" src={asset('olga-office.webp')} alt="Ольга Борзенкова у офиса"/></div><div className="officeMap"><MapPin size={34}/><h3>Как меня найти</h3><p>Постройте маршрут в удобном приложении.</p><div><a href="https://yandex.ru/maps/?text=%D0%98%D1%80%D0%BA%D1%83%D1%82%D1%81%D0%BA%2C%20%D1%83%D0%BB%D0%B8%D1%86%D0%B0%20%D0%93%D0%BE%D1%80%D0%BD%D0%B0%D1%8F%2C%2024" target="_blank" rel="noreferrer">Открыть в Яндекс Картах <ArrowRight size={16}/></a><a href="https://2gis.ru/irkutsk/search/%D0%98%D1%80%D0%BA%D1%83%D1%82%D1%81%D0%BA%20%D1%83%D0%BB%D0%B8%D1%86%D0%B0%20%D0%93%D0%BE%D1%80%D0%BD%D0%B0%D1%8F%2024" target="_blank" rel="noreferrer">Открыть в 2ГИС <ArrowRight size={16}/></a></div></div></section>
</main><footer><Logo/><a href="#documents">Документы</a><span>© 2026</span></footer></>}

function Article({post}:{post:typeof posts[0]}){return <><Header/><main className="article"><a href="#/" className="back">← Вернуться на главную</a><p className="eyebrow">{post.tag} · {post.read}</p><h1>{post.title}</h1><p className="articleLead">{post.lead}</p>{post.body.map(x=><p key={x}>{x}</p>)}<div className="articleCta"><h2>Сложность уже влияет на решение?</h2><a className="button copper" href="#/" onClick={()=>setTimeout(()=>document.getElementById('contact')?.scrollIntoView(),0)}>Записаться на встречу <ArrowRight size={18}/></a></div></main></>}
function App(){const [hash,setHash]=useState(location.hash);useEffect(()=>{const f=()=>{setHash(location.hash);if(location.hash==='#pricing'){requestAnimationFrame(()=>document.getElementById('pricing')?.scrollIntoView())}else{scrollTo(0,0)}};addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);const slug=hash.match(/^#\/blog\/(.+)$/)?.[1];const post=posts.find(p=>p.slug===slug);return post?<Article post={post}/>:<Home/>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
