import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, Menu, X, ChevronRight, Send, ShieldCheck, Scale, Users, Brain, BriefcaseBusiness} from 'lucide-react';
import './styles.css';

const asset=(name:string)=>`${import.meta.env.BASE_URL}assets/${name}`;

const segments=[
 {icon:BriefcaseBusiness,kicker:'Собственнику',title:'Я больше не могу управлять по-старому',text:'Когда внешне бизнес работает, а внутри уже нет сил, ясности и прежней опоры.',entry:'Карта кризиса собственника'},
 {icon:Users,kicker:'Партнёрам',title:'Конфликт уже дороже компромисса',text:'Когда спор соучредителей влияет на решения, команду, деньги и будущее компании.',entry:'Разобрать конфликт'},
 {icon:ChevronRight,kicker:'При смене роли',title:'Передать управление и не разрушить систему',text:'Когда пора выйти из операционки, определить новую роль и подготовить людей к переходу.',entry:'Карта передачи управления'},
 {icon:Scale,kicker:'Предпринимательской семье',title:'Развод, в котором есть не только чувства',text:'Когда переплетены дети, активы, репутация, бизнес и цена каждого решения.',entry:'Разделить эмоции и последствия'},
 {icon:Brain,kicker:'Руководителю',title:'Команда не выдерживает напряжения',text:'Когда формальная кадровая мера не решает конфликт и его системную причину.',entry:'Диагностика ситуации'}
];

const posts=[
 {slug:'ne-speshit',tag:'РЕШЕНИЯ',title:'Не спешить — не значит ничего не делать',lead:'Как отделить срочность эмоции от срочности решения и вернуть себе управляемость.',read:'6 минут',body:['В кризисе скорость легко спутать с эффективностью. Чем выше тревога, тем сильнее хочется немедленно закрыть вопрос — подписать, уволить, разорвать партнёрство или согласиться на первый предложенный сценарий.','Пауза нужна не для ухода от решения. Она нужна, чтобы разделить факты, интерпретации, риски и последствия. После этого действие становится не медленнее, а точнее.','Первый шаг — назвать, что именно требует решения сегодня, а что может подождать до появления полной картины.']},
 {slug:'konflikt-partnerov',tag:'ПАРТНЁРСТВО',title:'Когда конфликт партнёров становится проблемой бизнеса',lead:'Пять признаков, что личный спор уже меняет экономику и управление компанией.',read:'8 минут',body:['Конфликт становится бизнес-проблемой не в момент громкого разговора, а когда решения начинают приниматься в обход общей логики.','Сигналы: параллельные договорённости, задержка ключевых решений, борьба за лояльность команды, информационные закрытые зоны и перенос личных претензий в управленческие процедуры.','Работа начинается не с поиска виноватого, а с карты интересов, полномочий, рисков и минимально возможного соглашения.']},
 {slug:'tri-izmereniya',tag:'МЕТОД',title:'Почему одного специалиста иногда недостаточно',lead:'Что теряется, если смотреть на дорогой кризис только глазами права или только глазами психологии.',read:'7 минут',body:['Юридически безупречное решение может оказаться психологически неисполнимым. Психологически комфортное — создать правовые и управленческие риски.','Поэтому сложная ситуация рассматривается одновременно в трёх измерениях: человек, право и система. Это не замена профильных специалистов, а единая карта, которая помогает увидеть связи между их рекомендациями.','Цель — решение, которое клиент понимает, принимает и способен выполнить.']}
];

const products=[
 {kicker:'ЛЁГКИЙ ПЛАТНЫЙ ВХОД',title:'Карта решения',price:'Пилот · 4 900 ₽',text:'35–45 минут и письменная карта: факты, главный узел, цена паузы, зона контроля и ближайший исполнимый шаг.',cta:'Написать «КАРТА»',word:'КАРТА'},
 {kicker:'ОСНОВНОЙ B2C-ПРОДУКТ',title:'Точка ясности',price:'4 недели · пилот 39 000 ₽',text:'Четыре встречи, критерии решения, подготовка сложного разговора и план действий на ближайшие 30 дней.',cta:'Узнать о спринте',word:'ТОЧКА ЯСНОСТИ'},
 {kicker:'ОСНОВНОЙ B2B-ПРОДУКТ',title:'Передача без потери',price:'Диагностика · пилот 120 000 ₽',text:'Карта полномочий, риски перехода, правила эскалации и дорожная карта передачи управления на 30/60/90 дней.',cta:'Запросить описание',word:'ПЕРЕДАЧА'}
];

function Logo(){return <a className="logo" href="#top"><span>ОЛЬГА</span><small>БОРЗЕНКОВА</small></a>}
function Header(){const [open,setOpen]=useState(false);return <header><Logo/><button className="menuButton" aria-label="Меню" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''} onClick={()=>setOpen(false)}><a href="#approach">Подход</a><a href="#situations">Ситуации</a><a href="#products">Форматы</a><a href="#about">Об Ольге</a><a href="#blog">Блог</a><a className="navCta" href="#contact">Начать с карты</a></nav></header>}
function Home(){return <><div id="top"/><section className="hero"><Header/><div className="heroShade"/><div className="heroCopy"><p className="eyebrow light">СЛОЖНЫЕ РЕШЕНИЯ СОБСТВЕННИКА · ЧЕЛОВЕК, РОЛИ И СИСТЕМА БИЗНЕСА</p><h1>Вернуть ясность.<br/>Принять решение.<br/><em>Провести перемену.</em></h1><p className="heroAlt">Когда личное и деловое уже нельзя разделить.</p><p className="heroText">Помогаю увидеть ситуацию целиком, отделить факты от тревоги и собрать исполнимый следующий шаг — без готовых рецептов и давления.</p><a className="button copper" href="#situations">Найти свою ситуацию <ArrowRight size={18}/></a></div></section>
<main>
<section className="statement" id="approach"><p className="eyebrow">ГЛАВНЫЙ ПРИНЦИП</p><h2>Вам не нужно выбирать,<br/>что важнее: <em>человек, закон или бизнес.</em></h2><p>Решение должно выдерживать все три измерения.</p><div className="triad"><div><span>01</span><h3>Человек</h3><p>Эмоции, мотивы, пределы и способность выполнить решение.</p></div><div><span>02</span><h3>Право</h3><p>Последствия, риски, границы и корректная маршрутизация.</p></div><div><span>03</span><h3>Система</h3><p>Бизнес, роли, команда, договорённости и реализация изменения.</p></div></div></section>
<section className="situations" id="situations"><div className="sectionHead"><p className="eyebrow">ЛЁГКИЕ ВХОДЫ</p><h2>С какой ситуацией<br/>вы пришли?</h2><p>Не обязательно заранее знать название услуги. В первом цикле основной фокус — кризис роли собственника и передача управления.</p></div><div className="segmentGrid">{segments.map((s,i)=><article className={`segment ${i===0||i===2?'priority':''}`} key={s.title}><s.icon size={25}/><p className="eyebrow">{s.kicker}</p><h3>{s.title}</h3><p>{s.text}</p><a href={`https://t.me/Olga_Sergeevna_Borzenkova?text=${encodeURIComponent('Здравствуйте, Ольга. Хочу обсудить: '+s.title)}`} target="_blank" rel="noreferrer">{s.entry}<ArrowRight size={17}/></a><span className="number">0{i+1}</span></article>)}</div></section>
<section className="products" id="products"><div className="sectionHead"><p className="eyebrow">ПУТЬ БЕЗ ТЯЖЁЛОГО ВХОДА</p><h2>Начать с понятного<br/><em>следующего шага</em></h2><p>Не нужно сразу покупать длительное сопровождение. Сначала можно увидеть способ работы Ольги и получить конкретный материальный результат.</p></div><div className="productGrid">{products.map(p=><article className="product" key={p.title}><p className="eyebrow">{p.kicker}</p><h3>{p.title}</h3><strong>{p.price}</strong><p>{p.text}</p><a href={`https://t.me/Olga_Sergeevna_Borzenkova?text=${encodeURIComponent('Здравствуйте, Ольга. '+p.word)}`} target="_blank" rel="noreferrer">{p.cta}<ArrowRight size={17}/></a></article>)}</div><p className="pilotNote">Цены обозначены как пилотные и окончательно утверждаются перед запуском.</p></section>
<section className="about" id="about"><div className="aboutPhoto"><img src={asset('olga-portrait-master.png')} alt="Ольга Борзенкова"/></div><div className="aboutCopy"><p className="eyebrow">ОБ ОЛЬГЕ</p><h2>Спокойная сила<br/>в сложном разговоре</h2><p>Ольга Борзенкова — кризисный консультант для собственников и руководителей. В её подходе соединяются 22 года юридической практики, опыт кадровых и управленческих решений и профессиональная психологическая подготовка.</p><p>Она помогает увидеть ситуацию целиком: что происходит с человеком, какие последствия имеет выбор и как он повлияет на бизнес, команду или семью.</p><ul><li><ShieldCheck/>Конфиденциальность и ясные границы работы</li><li><Scale/>Право и переговоры с предпринимателями</li><li><Brain/>Психологическая и системная оптика</li></ul></div></section>
<section className="process"><p className="eyebrow light">КАК ЭТО РАБОТАЕТ</p><h2>Структурировать.<br/><em>Договориться.</em><br/>Провести перемену.</h2><div className="processSteps"><div><b>01</b><h3>Собираем картину</h3><p>Отделяем факты, интерпретации, эмоции и реальные ограничения.</p></div><div><b>02</b><h3>Видим сценарии</h3><p>Оцениваем последствия для человека, права и всей системы.</p></div><div><b>03</b><h3>Фиксируем маршрут</h3><p>Определяем следующий шаг, границы и необходимые договорённости.</p></div></div></section>
<section className="blog" id="blog"><div className="sectionHead"><p className="eyebrow">ЛИЧНЫЙ БЛОГ ПСИХОЛОГА</p><h2>Психология:<br/><em>великая и ужасная</em></h2><p>О власти, страхе, решениях, конфликтах и тёмной стороне человеческого поведения — без диагнозов по аватарке.</p></div><div className="postGrid">{posts.map(p=><a className="post" href={`#/blog/${p.slug}`} key={p.slug}><span>{p.tag}</span><h3>{p.title}</h3><p>{p.lead}</p><small>{p.read} <ArrowRight size={15}/></small></a>)}</div></section>
<section className="contact" id="contact"><div><p className="eyebrow light">ПЕРВЫЙ ШАГ</p><h2>Начните с<br/>«Карты решения».</h2><p>Короткий структурный разбор без обещаний мгновенного результата и навязанных услуг. Если задача требует другого специалиста, Ольга скажет об этом прямо.</p></div><a className="button ivory" href={`https://t.me/Olga_Sergeevna_Borzenkova?text=${encodeURIComponent('Здравствуйте, Ольга. КАРТА')}`} target="_blank" rel="noreferrer"><Send size={18}/> Написать «КАРТА»</a></section>
</main><footer><Logo/><p>Кризисное консультирование не заменяет медицинскую, психотерапевтическую или специализированную юридическую помощь.</p><span>© 2026</span></footer></>}

function Article({post}:{post:typeof posts[0]}){return <><Header/><main className="article"><a href="#/" className="back">← Вернуться на главную</a><p className="eyebrow">{post.tag} · {post.read}</p><h1>{post.title}</h1><p className="articleLead">{post.lead}</p>{post.body.map(x=><p key={x}>{x}</p>)}<div className="articleCta"><h2>Сложность уже влияет на решение?</h2><a className="button copper" target="_blank" rel="noreferrer" href="https://t.me/Olga_Sergeevna_Borzenkova">Обсудить с Ольгой <ArrowRight size={18}/></a></div></main></>}
function App(){const [hash,setHash]=useState(location.hash);useEffect(()=>{const f=()=>{setHash(location.hash);scrollTo(0,0)};addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);const slug=hash.match(/^#\/blog\/(.+)$/)?.[1];const post=posts.find(p=>p.slug===slug);return post?<Article post={post}/>:<Home/>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
