import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, Menu, X, ChevronRight, Send, ShieldCheck, Scale, Users, Brain, BriefcaseBusiness, MapPin, Mail} from 'lucide-react';
import './styles.css';

const asset=(name:string)=>`${import.meta.env.BASE_URL}assets/${name}`;

const segments=[
 {icon:BriefcaseBusiness,kicker:'Собственнику',title:'Я больше не могу управлять по-старому',text:'Когда внешне бизнес работает, а внутри уже нет сил, ясности и прежней опоры.',entry:'Карта кризиса собственника'},
 {icon:Users,kicker:'Партнёрам',title:'Конфликт уже дороже компромисса',text:'Когда спор соучредителей влияет на решения, команду, деньги и будущее компании.',entry:'Разобрать конфликт'},
 {icon:ChevronRight,kicker:'При смене роли',title:'Передать управление и не разрушить систему',text:'Когда пора выйти из операционки, определить новую роль и подготовить людей к переходу.',entry:'Карта передачи управления'},
 {icon:Scale,kicker:'Предпринимательской семье',title:'Развод, в котором есть не только чувства',text:'Когда переплетены дети, активы, репутация, бизнес и цена каждого решения.',entry:'Разделить эмоции и последствия'},
 {icon:Brain,kicker:'Руководителю',title:'Команда не выдерживает напряжения',text:'Когда формальная кадровая мера не решает конфликт и его системную причину.',entry:'Диагностика ситуации'}
];

const personalSituations=[
 {title:'Не понимаю, куда двигаться дальше',text:'Когда прежние ориентиры больше не помогают, а новое решение ещё не появилось.'},
 {title:'Тревога не отпускает',text:'Когда мысли постоянно возвращаются к плохому сценарию и трудно почувствовать опору.'},
 {title:'Отношения стали источником боли',text:'Когда разговоры не помогают, близость исчезает или один и тот же конфликт повторяется.'},
 {title:'Переживаю расставание или развод',text:'Когда нужно выдержать перемены, сохранить себя и принимать непростые решения.'},
 {title:'Трудно защищать свои границы',text:'Когда сложно отказать, попросить о важном или перестать жить по чужим ожиданиям.'},
 {title:'Внешне всё хорошо, а внутри пусто',text:'Когда привычная жизнь продолжается, но в ней больше нет радости, смысла или живого интереса.'}
];

const psychologistLegalSituations=[
 {title:'Договор с клиентом',text:'Подготовка понятных условий работы: формат встреч, оплата, отмена, перенос и границы ответственности.'},
 {title:'Персональные данные',text:'Согласия, анкеты и правила хранения информации, которую психолог получает от клиента.'},
 {title:'Сайт и запись на консультацию',text:'Проверка формы записи, обязательных документов, описания услуг и публичных текстов.'},
 {title:'Конфликт или претензия клиента',text:'Разбор ситуации, переписки и возможных действий без лишней эскалации.'},
 {title:'Начало частной практики',text:'Юридическая основа работы, порядок оплаты и документы, необходимые на старте.'},
 {title:'Реклама и экспертный контент',text:'Проверка формулировок, обещаний результата и границ между психологической и медицинской помощью.'}
];

const posts=[
 {slug:'ne-speshit',tag:'РЕШЕНИЯ',title:'Не спешить — не значит ничего не делать',lead:'Как отделить срочность эмоции от срочности решения и вернуть себе управляемость.',read:'6 минут',body:['В кризисе скорость легко спутать с эффективностью. Чем выше тревога, тем сильнее хочется немедленно закрыть вопрос — подписать, уволить, разорвать партнёрство или согласиться на первый предложенный сценарий.','Пауза нужна не для ухода от решения. Она нужна, чтобы разделить факты, интерпретации, риски и последствия. После этого действие становится не медленнее, а точнее.','Первый шаг — назвать, что именно требует решения сегодня, а что может подождать до появления полной картины.']},
 {slug:'konflikt-partnerov',tag:'ПАРТНЁРСТВО',title:'Когда конфликт партнёров становится проблемой бизнеса',lead:'Пять признаков, что личный спор уже меняет экономику и управление компанией.',read:'8 минут',body:['Конфликт становится бизнес-проблемой не в момент громкого разговора, а когда решения начинают приниматься в обход общей логики.','Сигналы: параллельные договорённости, задержка ключевых решений, борьба за лояльность команды, информационные закрытые зоны и перенос личных претензий в управленческие процедуры.','Работа начинается не с поиска виноватого, а с карты интересов, полномочий, рисков и минимально возможного соглашения.']},
 {slug:'tri-izmereniya',tag:'МЕТОД',title:'Почему одного специалиста иногда недостаточно',lead:'Что теряется, если смотреть на дорогой кризис только глазами права или только глазами психологии.',read:'7 минут',body:['Юридически безупречное решение может оказаться психологически неисполнимым. Психологически комфортное — создать правовые и управленческие риски.','Поэтому сложная ситуация рассматривается одновременно в трёх измерениях: человек, право и система. Это не замена профильных специалистов, а единая карта, которая помогает увидеть связи между их рекомендациями.','Цель — решение, которое клиент понимает, принимает и способен выполнить.']}
];

const products=[
 {kicker:'ЛЁГКИЙ ПЛАТНЫЙ ВХОД',title:'Карта решения',price:'Пилот · 4 900 ₽',text:'35–45 минут и письменная карта: факты, главный узел, цена паузы, зона контроля и ближайший исполнимый шаг.'},
 {kicker:'ОСНОВНОЙ B2C-ПРОДУКТ',title:'Точка ясности',price:'4 недели · пилот 39 000 ₽',text:'Четыре встречи, критерии решения, подготовка сложного разговора и план действий на ближайшие 30 дней.'},
 {kicker:'ОСНОВНОЙ B2B-ПРОДУКТ',title:'Передача без потери',price:'Диагностика · пилот 120 000 ₽',text:'Карта полномочий, риски перехода, правила эскалации и дорожная карта передачи управления на 30/60/90 дней.'}
];

function Logo(){return <a className="logo" href="#top"><span>ОЛЬГА</span><small>БОРЗЕНКОВА</small></a>}
function Header(){const [open,setOpen]=useState(false);return <header><div className="headerBrand"><Logo/><span className="headerRole">Кризисный консультант с высшим юридическим и психологическим образованием</span></div><button className="menuButton" aria-label="Меню" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''} onClick={()=>setOpen(false)}><a href="#contact">Контакты</a><a href="#socials">Социальные сети</a><a className="navCta" href="#contact">Записаться на встречу</a><a href="#documents">Документы</a><a href="#office">Адрес</a></nav></header>}

function Home(){return <><div id="top"/><section className="hero"><Header/><div className="heroShade"/><div className="heroCopy"><p className="eyebrow light">ЧЕЛОВЕК · СИСТЕМА · ПРАВО</p><h1>Вернуть ясность.<br/>Принять решение.<br/>Реализовать принятое решение.</h1><div className="heroActions"><a className="button copper" href="#personal">Личные вопросы <ArrowRight size={18}/></a><a className="button outline" href="#business">Бизнес <ArrowRight size={18}/></a><a className="button outline" href="#psychologist-law">Юрист для психологов <ArrowRight size={18}/></a></div></div></section>
<main>
<section className="statement" id="approach"><p className="eyebrow">ГЛАВНЫЙ ПРИНЦИП</p><h2>У каждой сложной ситуации<br/><em>три измерения.</em></h2><p>Хорошее решение должно учитывать их одновременно.<br/>Мы не отделяем личные переживания от реальной ситуации.</p><div className="triad"><div><span>01</span><h3>Человек</h3><p>Его чувства, мотивы, потребности и способность выполнить решение.</p></div><div><span>02</span><h3>Система</h3><p>Семья, бизнес, общество и государство: связи, роли и последствия для других людей.</p></div><div><span>03</span><h3>Право</h3><p>Юридические риски, обязанности, границы и действия, необходимые для реализации решения.</p></div></div></section>
<section className="directions"><div className="sectionHead"><p className="eyebrow">ТРИ НАПРАВЛЕНИЯ РАБОТЫ</p><h2>С чем вы хотите<br/><em>разобраться?</em></h2><p>Какой бы путь вы ни выбрали, мы будем смотреть на ситуацию целиком: что происходит с человеком, как устроена окружающая его система и какие правовые последствия может иметь решение.</p></div><div className="directionGrid"><a href="#personal" className="directionCard personalDirection"><span>01</span><h3>Личные вопросы</h3><p>Человек, его отношения и жизненные решения — с учётом интересов семьи, работы и возможных последствий.</p><b>Посмотреть ситуации <ArrowRight size={17}/></b></a><a href="#business" className="directionCard businessDirection"><span>02</span><h3>Бизнес</h3><p>Собственник, команда и компания — с учётом человеческих мотивов, бизнес-процессов и требований законодательства.</p><b>Посмотреть ситуации <ArrowRight size={17}/></b></a><a href="#psychologist-law" className="directionCard legalDirection"><span>03</span><h3>Юрист для психологов</h3><p>Создание юридически защищённой системы частной практики с учётом прав и законных интересов психолога и клиента.</p><b>Посмотреть ситуации <ArrowRight size={17}/></b></a></div></section>
<section className="personalServices" id="personal"><div className="sectionIntroWithPhoto"><div className="sectionHead"><p className="eyebrow">ЛИЧНЫЕ ВОПРОСЫ</p><h2>Когда важно разобраться<br/><em>в себе и своей жизни</em></h2></div><img className="sectionInsetPhoto wideCrop" src={asset('olga-personal-photo-3.jpg')} alt="Ольга Борзенкова"/></div><div className="personalGrid">{personalSituations.map((s,i)=><article className="personalCard" key={s.title}><span>0{i+1}</span><h3>{s.title}</h3><p>{s.text}</p><a href="#contact">Обсудить на встрече <ArrowRight size={17}/></a></article>)}</div></section>
<section className="situations" id="business"><div className="sectionIntroWithPhoto"><div className="sectionHead"><p className="eyebrow">БИЗНЕС</p><h2>Когда решение влияет<br/>не только на вас</h2><p>В бизнесе личное решение собственника меняет всю систему: команду, деньги, отношения и ответственность. Поэтому мы одновременно учитываем человека, устройство бизнеса и право.</p></div><img className="sectionInsetPhoto" src={asset('olga-principle.webp')} alt="Ольга Борзенкова за шахматной доской"/></div><div className="segmentGrid">{segments.map((s,i)=><article className={`segment ${i===0||i===2?'priority':''}`} key={s.title}><s.icon size={25}/><p className="eyebrow">{s.kicker}</p><h3>{s.title}</h3><p>{s.text}</p><a href="#contact">Записаться на встречу<ArrowRight size={17}/></a><span className="number">0{i+1}</span></article>)}</div></section>
<section className="lawForPsychologists" id="psychologist-law"><div className="sectionIntroWithPhoto"><div className="sectionHead"><p className="eyebrow">ЮРИСТ ДЛЯ ПСИХОЛОГОВ</p><h2>Чтобы практика была<br/><em>понятной и защищённой</em></h2><p>Документы должны защищать право, поддерживать рабочую систему и оставаться понятными живым людям — психологу и его клиенту.</p></div><img className="sectionInsetPhoto" src={asset('olga-hero-natural-face-v5.webp')} alt="Ольга Борзенкова в рабочем кабинете"/></div><div className="legalGrid">{psychologistLegalSituations.map((s,i)=><article className="legalCard" key={s.title}><span>0{i+1}</span><h3>{s.title}</h3><p>{s.text}</p><a href="#contact">Обсудить задачу <ArrowRight size={17}/></a></article>)}</div></section>
<section className="about" id="about"><div className="aboutPhoto"><img src={asset('olga-about.webp')} alt="Ольга Борзенкова"/></div><div className="aboutCopy"><p className="eyebrow">ОБ ОЛЬГЕ</p><h2>От права —<br/>к пониманию человека</h2><p>Профессиональный путь Ольги начался с права. В 2004 году она окончила Юридический институт Иркутского государственного университета, а в 2007 году — аспирантуру Байкальского государственного университета по уголовному праву и криминологии.</p><p>Более 22 лет Ольга работает в корпоративном праве и адвокатуре. За это время она сопровождала нефтяные компании, строительные холдинги и вузы, представляла интересы клиентов в судах и на переговорах. Преподавала в университете уголовное и трудовое право, а также арбитражный процесс.</p><p>Многолетняя юридическая практика показала: в основе сложного решения всегда находится человек — с его чувствами, страхами, отношениями и ответственностью. Поэтому психологическое образование стало для Ольги не сменой профессии, а её естественным продолжением. Она окончила Иркутский государственный университет по направлению психологии, а в 2024 году прошла обучение и Всероссийскую аттестацию специалистов по управлению персоналом.</p><p className="aboutMission">«Моя задача — помогать людям проходить через кризисы, сохраняя себя».</p><p>У Ольги четверо детей. Она знает не только из профессионального опыта, что такое ответственность, перемены и умение сохранять ясность, когда привычный порядок меняется.</p><ul><li><Brain/>Человек: чувства, мотивы и способность действовать</li><li><Users/>Система: семья, бизнес, общество и государство</li><li><Scale/>Право: риски, границы и юридические действия</li></ul></div></section>
<section className="agreements" id="agreements"><div className="sectionHead"><p className="eyebrow">НАШИ ДОГОВОРЁННОСТИ</p><h2>Чтобы в нашей работе<br/><em>было всё понятно</em></h2><p>До начала встреч мы заранее обсуждаем формат работы и одинаково понимаем её границы.</p></div><div className="agreementGrid"><article><span>01</span><h3>Конфиденциальность</h3><p>Содержание встречи и полученная информация остаются строго между нами.</p></article><article><span>02</span><h3>Время встречи</h3><p>Мы заранее согласовываем продолжительность, место или способ связи и бережно относимся ко времени друг друга.</p></article><article><span>03</span><h3>Отмена и перенос</h3><p>Порядок отмены, переноса и оплаты пропущенной встречи будет прямо указан в договоре.</p></article><article><span>04</span><h3>Связь между встречами</h3><p>Мы заранее договариваемся, по каким вопросам и каким способом можно связаться вне назначенного времени.</p></article><article><span>05</span><h3>Честный разговор</h3><p>Вы можете говорить, если формат, темп или направление работы вам не подходят. Это важная часть совместной работы.</p></article><article><span>06</span><h3>Ясные границы помощи</h3><p>Если вопрос требует врача или другого специалиста, я скажу об этом прямо и предложу подходящий следующий шаг.</p></article></div><p className="draftNote">Проект раздела. Окончательные условия будут утверждены вместе с договором.</p></section>
<section className="documents" id="documents"><div className="sectionHead"><p className="eyebrow light">ДОКУМЕНТЫ</p><h2>Всё важное —<br/><em>до первой встречи</em></h2><p>Здесь будут размещены документы, с которыми можно спокойно ознакомиться заранее. Конкретный комплект зависит от выбранного направления работы.</p></div><div className="documentGrid"><article><Scale size={28}/><h3>Договор об оказании услуг</h3><p>Предмет работы, формат встреч, стоимость, порядок оплаты, отмены и прекращения работы.</p><span>Готовится к публикации</span></article><article><ShieldCheck size={28}/><h3>Согласие на обработку данных</h3><p>Какие сведения нужны для записи, для чего они используются и как защищаются.</p><span>Готовится к публикации</span></article><article><Brain size={28}/><h3>Информированное согласие</h3><p>Возможности и границы психологического консультирования, права клиента и порядок взаимодействия.</p><span>Готовится к публикации</span></article></div><p className="draftNote light">Ссылки на документы появятся после утверждения окончательных текстов.</p></section>
<section className="blog" id="blog"><div className="sectionHead"><p className="eyebrow">ЛИЧНЫЙ БЛОГ ПСИХОЛОГА</p><h2>Психология:<br/><em>великая и ужасная</em></h2><p>О том, как внутренние переживания человека становятся решениями, меняют систему отношений и иногда приводят к правовым последствиям.</p></div><div className="postGrid">{posts.map(p=><a className="post" href={`#/blog/${p.slug}`} key={p.slug}><span>{p.tag}</span><h3>{p.title}</h3><p>{p.lead}</p><small>{p.read} <ArrowRight size={15}/></small></a>)}</div></section>
<section className="socials" id="socials"><div className="sectionHead"><p className="eyebrow">ОСТАВАЙТЕСЬ НА СВЯЗИ</p><h2>Больше мыслей и разговоров<br/><em>в моих каналах.</em></h2><p>Выберите удобную площадку — короткие видео, заметки и материалы о сложных решениях.</p></div><div className="socialGrid"><a href="https://youtube.com/channel/UC2ZPOXNBx7PzwgtqHkazaRg?si=ESOn5pOVVXnTy_wx" target="_blank" rel="noreferrer"><span className="socialMark">YT</span><span>YouTube</span><ArrowRight size={17}/></a><a href="https://www.instagram.com/tochkayasno?utm_source=qr" target="_blank" rel="noreferrer"><span className="socialMark">IG</span><span>Instagram</span><ArrowRight size={17}/></a><a href="https://m.tenchat.ru/u/lo5xce9o" target="_blank" rel="noreferrer"><span className="socialMark">T</span><span>TenChat</span><ArrowRight size={17}/></a><a href="https://max.ru/join/nt1En70ad4uq4RO3Rh2e1HK0SFfUoISLDRxKTrJoL-A" target="_blank" rel="noreferrer"><span className="socialMark">M</span><span>MAX канал</span><ArrowRight size={17}/></a><a href="https://t.me/tochkayasno" target="_blank" rel="noreferrer"><span className="socialMark">TG</span><span>Telegram канал</span><ArrowRight size={17}/></a></div></section>
<section className="contact" id="contact"><div className="contactIntro"><p className="eyebrow light">ПЕРВЫЙ ШАГ</p><h2>Записаться<br/>на встречу.</h2><p>Коротко опишите ситуацию. На встрече мы рассмотрим её в трёх измерениях: человек, система и право — и определим понятный следующий шаг.</p></div><a className="button ivory" href="https://t.me/Olga_Sergeevna_Borzenkova" target="_blank" rel="noreferrer"><Send size={18}/>Записаться на встречу</a></section>
<section className="office" id="office"><div className="officeTitle"><p className="eyebrow">ЛИЧНАЯ ВСТРЕЧА</p><h2>Пространство для<br/><em>важного разговора.</em></h2><p>г. Иркутск, ул. Горная, 24<br/>бизнес-центр «Зеркальный», 8 этаж, офис 804</p><img className="officePhoto" src={asset('olga-office.webp')} alt="Ольга Борзенкова у офиса"/></div><div className="officeMap"><MapPin size={34}/><h3>Как нас найти</h3><p>Постройте маршрут в удобном приложении.</p><div><a href="https://yandex.ru/maps/?text=%D0%98%D1%80%D0%BA%D1%83%D1%82%D1%81%D0%BA%2C%20%D1%83%D0%BB%D0%B8%D1%86%D0%B0%20%D0%93%D0%BE%D1%80%D0%BD%D0%B0%D1%8F%2C%2024" target="_blank" rel="noreferrer">Открыть в Яндекс Картах <ArrowRight size={16}/></a><a href="https://2gis.ru/irkutsk/search/%D0%98%D1%80%D0%BA%D1%83%D1%82%D1%81%D0%BA%20%D1%83%D0%BB%D0%B8%D1%86%D0%B0%20%D0%93%D0%BE%D1%80%D0%BD%D0%B0%D1%8F%2024" target="_blank" rel="noreferrer">Открыть в 2ГИС <ArrowRight size={16}/></a></div></div></section>
</main><footer><Logo/><a href="#documents">Документы</a><span>© 2026</span></footer></>}

function Article({post}:{post:typeof posts[0]}){return <><Header/><main className="article"><a href="#/" className="back">← Вернуться на главную</a><p className="eyebrow">{post.tag} · {post.read}</p><h1>{post.title}</h1><p className="articleLead">{post.lead}</p>{post.body.map(x=><p key={x}>{x}</p>)}<div className="articleCta"><h2>Сложность уже влияет на решение?</h2><a className="button copper" href="#/" onClick={()=>setTimeout(()=>document.getElementById('contact')?.scrollIntoView(),0)}>Записаться на встречу <ArrowRight size={18}/></a></div></main></>}
function App(){const [hash,setHash]=useState(location.hash);useEffect(()=>{const f=()=>{setHash(location.hash);scrollTo(0,0)};addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);const slug=hash.match(/^#\/blog\/(.+)$/)?.[1];const post=posts.find(p=>p.slug===slug);return post?<Article post={post}/>:<Home/>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
